import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-2 justify-center text-xl">
          <Link href="/">Home</Link>
          <p>about</p>
          <p>report</p>
          <Link href="/todos-csr">todos-csr</Link>
          <Link href="/todos-ssr">todos-ssr</Link>
        </nav>
        <hr />
        {children}
      </body>
    </html>
  );
}
